Create a vector with values ranging from 10 to 49.



In [1]:
import numpy as np

array1 = np.arange(10, 49, 1)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Create a 3x3 matrix with values ranging from 0 to 8.


In [7]:
arr2 = np.arange(0, 9, 1, dtype=int)
matrix1 = arr2.reshape((3,3))
print(matrix1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


np.int64(7)

Create a 3x3 identity matrix.


In [9]:
i_matrix = np.identity(3, dtype=int)
print(i_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Create a 3x3x3 array with random values.


In [11]:
arr3 = np.empty((3,3,3))
print(arr3)

[[[1.07684688e-311 1.07684269e-311 1.69121096e-306]
  [9.34609111e-307 1.42413555e-306 1.78019082e-306]
  [1.37959740e-306 6.23057349e-307 1.02360935e-306]]

 [[1.69120416e-306 1.78022342e-306 6.23058028e-307]
  [1.06811422e-306 9.45699680e-308 1.11258854e-306]
  [1.11261502e-306 1.42410839e-306 7.56597770e-307]]

 [[6.23059726e-307 1.42419530e-306 8.45592576e-307]
  [6.23054972e-307 1.42421160e-306 1.24610723e-306]
  [9.34609111e-307 2.22522596e-306 3.91786943e-317]]]


Create a 10x10 array with random values and find the minimum and maximum values.


In [25]:
arr4 = np.random.random((10,10))
max_num = arr4.max()
min_num = arr4.min()
print(max_num, min_num)

0.9840627903723058 0.0009573119490965398


Create a random vector of size 30 and find the mean value.


In [23]:
arr5 = np.random.random(10)
print(arr5)
print(arr5.sum()/10)

[0.17980523 0.81815234 0.75647013 0.27900547 0.20565915 0.24061064
 0.13891071 0.84388352 0.84000789 0.64620034]
0.4948705419628599


Normalize a 5x5 random matrix.


In [29]:
matrix2 = np.random.randint(100, size=(5,5))
print(matrix2)
max_n = matrix2.max()
min_n = matrix2.min()
matrix2 = (matrix2-min_n)/(max_n-min_n)
print(matrix2)

[[32 24 71 35 89]
 [ 2  0 31 58 54]
 [53 11 25 37 67]
 [90 48 13 91 94]
 [10 47  3 48 18]]
[[0.34042553 0.25531915 0.75531915 0.37234043 0.94680851]
 [0.0212766  0.         0.32978723 0.61702128 0.57446809]
 [0.56382979 0.11702128 0.26595745 0.39361702 0.71276596]
 [0.95744681 0.5106383  0.13829787 0.96808511 1.        ]
 [0.10638298 0.5        0.03191489 0.5106383  0.19148936]]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [40]:
m1 = np.random.randint(10, size=(5,3))
m2 = np.random.randint(10, size=(3,2))
print("m1 ")
print(m1)
print("m2 ")
print(m2)
product = np.matmul(m1, m2)
print("product")
print(product)

m1 
[[8 9 4]
 [4 5 5]
 [9 3 2]
 [3 5 2]
 [6 9 7]]
m2 
[[1 9]
 [9 2]
 [5 9]]
product
[[109 126]
 [ 74  91]
 [ 46 105]
 [ 58  55]
 [122 135]]



Create two 3x3 matrices and compute their dot product.


In [39]:
p = np.random.randint(10, size=(3,3))
q = np.random.randint(10, size=(3,3))
print(p)
print(q, "\n")
print(np.dot(p, q))


[[1 2 4]
 [0 9 7]
 [7 3 4]]
[[5 2 6]
 [7 4 1]
 [5 7 5]] 

[[39 38 28]
 [98 85 44]
 [76 54 65]]


Given a 4x4 matrix, find its transpose.


In [41]:
mat4 = np.random.randint(10, size=(4,4))
print(mat4)
print("Transpose:")
print(np.transpose(mat4))

[[8 2 7 8]
 [6 5 5 1]
 [5 1 0 2]
 [1 8 9 4]]
Transpose:
[[8 6 5 1]
 [2 5 1 8]
 [7 5 0 9]
 [8 1 2 4]]


Create a 3x3 matrix and calculate its determinant.


In [42]:
print(p)
print("Determinant is ", np.linalg.det(mat4))

[[1 2 4]
 [0 9 7]
 [7 3 4]]
Determinant is  -914.9999999999997


Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).


In [44]:
a = np.random.randint(10, size=(3,4))
b = np.random.randint(10, size=(4,3))
print(a)
print(b)
print("Product")
print(np.matmul(a,b))

[[1 9 7 8]
 [3 6 9 5]
 [0 6 7 7]]
[[4 2 5]
 [8 8 6]
 [3 4 7]
 [0 3 8]]
Product
[[ 97 126 172]
 [ 87 105 154]
 [ 69  97 141]]


Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.


In [46]:
print(q)
vec = np.array([1,2,3]).reshape(3,1)
print(vec)
print(q*vec)

[[5 2 6]
 [7 4 1]
 [5 7 5]]
[[1]
 [2]
 [3]]
[[ 5  2  6]
 [14  8  2]
 [15 21 15]]


Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.


In [49]:
A = np.array([[7, 4, 8],
              [5, 7, 3],
              [7, 8, 5]])

b = np.array([[4],
              [8],
              [8]])

x = np.linalg.solve(A,b)
print(x)


[[-4.        ]
 [ 2.90909091]
 [ 2.54545455]]


Given a 5x5 matrix, find the row-wise and column-wise sums.

In [52]:
a = np.random.randint(6, size=(5,5))
print(a)
row_sum = np.sum(a, axis=1)
col_rum = np.sum(a, axis=0)
print(row_sum, col_rum)

[[0 3 2 2 5]
 [2 4 4 2 3]
 [5 2 4 1 4]
 [2 3 4 5 4]
 [4 2 3 2 5]]
[12 15 16 18 16] [13 14 17 12 21]
